version: '3.8'

services:
  # MongoDB database
  mongo:
    image: mongo:latest
    container_name: flappy-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - flappy-network
    restart: unless-stopped
    environment:
      - TZ=UTC

  # Machine Learning Client
  ml-client:
    build: 
      context: ./machine-learning-client
      dockerfile: Dockerfile
    container_name: flappy-ml-client
    ports:
      - "5002:5002"  # Expose API port
    volumes:
      - ./machine-learning-client:/app
      - ./dataset:/app/dataset
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=voice_flappy_game
      - MODEL_PATH=/app/cnn_model.h5
      - ENCODER_PATH=/app/cnn_label_encoder.pkl
      - API_PORT=5002
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    networks:
      - flappy-network
    restart: unless-stopped
    command: python Client.py --api

  # Web App
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: flappy-web
    ports:
      - "5001:5001"
    volumes:
      - ./web-app:/app
    depends_on:
      - mongo
      - ml-client
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=voice_flappy_game
      - ML_CLIENT_API_URL=http://flappy-ml-client:5002/api/predict
      - FLASK_ENV=development
      - SECRET_KEY=dev_secret_key
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    networks:
      - flappy-network
    restart: unless-stopped

networks:
  flappy-network:
    driver: bridge

volumes:
  mongo-data: