name: Lint and Format

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-format-web-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd web-app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pylint
    - name: Run Black formatter
      run: |
        cd web-app
        black . --check
    - name: Run Pylint
      run: |
        cd web-app
        pylint --disable=C0111,C0103 *.py

  lint-and-format-machine-learning-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd machine-learning-client
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pylint
    - name: Run Black formatter
      run: |
        cd machine-learning-client
        black . --check
    - name: Run Pylint
      run: |
        cd machine-learning-client
        pylint --disable=C0111,C0103 *.py
