name: Lint and Format
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
permissions:
  contents: write
  
jobs:
  lint-and-format-web-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd web-app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install tomli black pylint
    - name: Lint with pylint
      run: |
        cd web-app
        python -m pylint --disable=C0111,C0103,C0303,W0621,E1101,C0415,C0301 --fail-under=6.0 *.py
      continue-on-error: true
    - name: Format with black
      run: |
        cd web-app
        python -m black .
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply black formatting" || echo "No changes to commit"
        git push || echo "No changes to push"
  lint-and-format-machine-learning-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd machine-learning-client
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install tomli black pylint
    - name: Lint with pylint
      run: |
        cd machine-learning-client
        python -m pylint --disable=C0111,C0103,C0303,W0621,E1101,C0301,E0401,E0611,R0914,W1203,W0612,W0611,R0801,C0304,W0718 --fail-under=6.0 *.py
      continue-on-error: true
    - name: Format with black
      run: |
        cd machine-learning-client
        python -m black .
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply black formatting" || echo "No changes to commit"
        git push || echo "No changes to push"
