name: ML Client CI
on:
  push:
    branches: 
      - main
      - '**'  # This will run on all branches
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client-ci.yml'
jobs:
  test-ml-client:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd machine-learning-client
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    
    - name: Test with pytest
      run: |
        cd machine-learning-client
        pytest test_client.py --cov=. --cov-report=xml
        
    - name: Display coverage report
      run: |
        cd machine-learning-client
        coverage report -m
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./machine-learning-client/coverage.xml
        flags: mlclient
        fail_ci_if_error: false
