name: Machine Learning Client CI

on:
  push:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      working-directory: ./machine-learning-client
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov black pylint
        pip install numpy tensorflow pymongo librosa python-dotenv joblib
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        fi
        
    - name: Run linter
      working-directory: ./machine-learning-client
      run: |
        pylint *.py || true
        
    - name: Run formatter check
      working-directory: ./machine-learning-client
      run: |
        black --check .
        
    - name: Run tests with coverage
      working-directory: ./machine-learning-client
      run: |
        pytest test_client.py --cov=Client --cov-report=xml
        
    - name: Check coverage threshold
      working-directory: ./machine-learning-client
      run: |
        coverage report --fail-under<80
