name: Machine Learning Client CI

on:
  push:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install black pylint
    - name: Lint machine learning client
      working-directory: ./machine-learning-client
      run: |
        black --check .
        pylint --disable=C0111,C0103,C0303 *.py || true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      working-directory: ./machine-learning-client
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install numpy tensorflow pymongo librosa python-dotenv joblib
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        fi
    - name: Run tests with coverage
      working-directory: ./machine-learning-client
      run: |
        pytest test_client.py --cov=Client --cov-report=xml --cov-report=term
        coverage report --fail-under=80

  build-container:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker container
      uses: docker/build-push-action@v4
      with:
        context: ./machine-learning-client
        file: ./machine-learning-client/Dockerfile
        push: false
        load: true
        tags: flappy-ml-client:test
    - name: Verify image
      run: docker images | grep flappy-ml-client
