name: Test and Coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-web-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd web-app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-flask pytest-cov
        pip install tensorflow  # Ensure TensorFlow is installed for tests
    - name: Run tests with coverage
      run: |
        cd web-app
        python -m pytest --cov=. --cov-report=xml
      continue-on-error: true  # Continue even if tests fail initially
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./web-app/coverage.xml
        flags: webapp
        name: web-app-coverage
        fail_ci_if_error: false

  test-machine-learning-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd machine-learning-client
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pip install tensorflow  # Ensure TensorFlow is installed for tests
    - name: Run tests with coverage
      run: |
        cd machine-learning-client
        python -m pytest --cov=. --cov-report=xml
      continue-on-error: true  # Continue even if tests fail initially
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./machine-learning-client/coverage.xml
        flags: mlclient
        name: ml-client-coverage
        fail_ci_if_error: false
