name: Web App CI
on:
  push:
    branches: 
      - main
      - '**'  # This will match any branch
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app-ci.yml'
  pull_request:
    branches: 
      - main
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app-ci.yml'
jobs:
  test-web-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd web-app
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-flask pytest-cov pydub

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Run tests with coverage
      run: |
        cd web-app
        coverage run --source=app -m pytest test_app.py -v
        coverage xml
        coverage report -m
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./web-app/coverage.xml
        flags: webapp
        fail_ci_if_error: false
