name: Web App CI

on:
  push:
    branches: [ main ]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web-app/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      working-directory: ./web-app
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-flask pytest-cov black pylint
        pip install flask flask-socketio pymongo python-dotenv joblib pydub
        pip install numpy tensorflow librosa
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        fi
        
    - name: Run linter
      working-directory: ./web-app
      run: |
        pylint *.py --disable=C0111,C0103,C0303,C0330 || true
        
    - name: Run formatter check
      working-directory: ./web-app
      run: |
        black --check .
        
    - name: Run tests with coverage
      working-directory: ./web-app
      run: |
        pytest --cov=app --cov-report=xml
        
    - name: Check coverage threshold
      working-directory: ./web-app
      run: |
        coverage report --fail-under=80
