name: Web App CI

on:
  push:
    branches: [ main ]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web-app/**'

jobs:
   test-web-app2:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd web-app
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
        pip install pytest pytest-flask pytest-cov
    
    - name: Test with pytest
      run: |
        cd web-app
        # Create an empty __init__.py file if it doesn't exist
        touch __init__.py
        # Make sure tests directory is a package
        touch tests/__init__.py
        # Copy app.py to the root if it's not already there
        if [ ! -f app.py ] && [ -f app/app.py ]; then cp app/app.py app.py; fi
        # Use PYTHONPATH to help Python find the modules
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest --maxfail=1 --disable-warnings -v tests/ --cov=. --cov-report=xml
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./web-app/coverage.xml
        flags: webapp
        fail_ci_if_error: false
